my_list=[]
my_list.insert(0,10)
my_list.insert(1,20)
my_list.insert(2,30)
my_list.insert(3,40)
print("List after Insertion:",my_list)
my_list.remove(20)
print("List after Removing 20:",my_list)
my_list.append(50)
print("List after appending 50:",my_list)
print("Length of list:",len(my_list))
popped_element=my_list.pop()
print("Element popped:",popped_element)
print("List after popping an element:",my_list)
my_list.clear()
print("my_list after clearing:",my_list)